### ISSUE TITLE
Supervised-only training on 1% data has very high results

### ISSUE THREAD

**Issue by Divadi** [THU17cyz/3DIoUMatch-PVRCNN#1]
Hello! Thank you for open-sourcing your codebase.

I have tried to use the repository to first do the pre-training phase on KITTI. 
Actually, first, the repository would not run automatically for me, so I had to make some changes:
https://github.com/THU17cyz/3DIoUMatch-PVRCNN/blob/b50d9fd932c42e6916d29ad7153f1d3ccbd55827/pcdet/datasets/kitti/kitti_dataset.py#L452
I changed to training=False (because otherwise, it kept looking for a "kitti_dbinfos_train.pkl", which for some reason I couldn't properly generate with the full split txt - it just gave me an empty list [])
Here:
https://github.com/THU17cyz/3DIoUMatch-PVRCNN/blob/b50d9fd932c42e6916d29ad7153f1d3ccbd55827/pcdet/datasets/kitti/kitti_dataset.py#L226
I added 
```
include_info_idxs = None
if len(self.sample_id_list[0].split(" ")) == 2: # means it's a split
    # generate stuff to include
    include_info_idxs = [int(line.split(" ")[1]) for line in self.sample_id_list]

for k in range(len(infos)):
    if include_info_idxs is not None:
        if k not in include_info_idxs:
            continue
```
because there didn't seem to be any code built-in for filtering just the frames inside the smaller split.

With these changes, I tried training on the provided 0.01_1 and 0.01_2 splits, and got:
Split 1:
```
Car AP@0.70, 0.70, 0.70:
bbox AP:97.0166, 88.4264, 87.7184
bev  AP:89.7851, 85.1410, 79.3515
3d   AP:88.5321, 77.2608, 75.0451
aos  AP:96.56, 87.50, 86.56
Car AP_R40@0.70, 0.70, 0.70:
bbox AP:98.1557, 91.4289, 89.1516
bev  AP:95.1296, 85.9902, 83.5684
3d   AP:91.6326, 79.0419, 74.8542
aos  AP:97.68, 90.40, 87.91
Car AP@0.70, 0.50, 0.50:
bbox AP:97.0166, 88.4264, 87.7184
bev  AP:97.0982, 88.7778, 88.4398
3d   AP:97.0132, 88.7039, 88.2761
aos  AP:96.56, 87.50, 86.56
Car AP_R40@0.70, 0.50, 0.50:
bbox AP:98.1557, 91.4289, 89.1516
bev  AP:98.2354, 93.8260, 91.6486
3d   AP:98.1979, 93.5422, 91.4403
aos  AP:97.68, 90.40, 87.91
Pedestrian AP@0.50, 0.50, 0.50:
bbox AP:50.1803, 49.5963, 45.4304
bev  AP:42.3984, 37.5393, 35.5838
3d   AP:39.5851, 34.8857, 30.8286
aos  AP:39.63, 38.13, 35.09
Pedestrian AP_R40@0.50, 0.50, 0.50:
bbox AP:49.2451, 46.8583, 44.1228
bev  AP:40.1931, 35.3439, 31.6750
3d   AP:36.0652, 31.3460, 28.2745
aos  AP:37.15, 34.31, 32.17
Pedestrian AP@0.50, 0.25, 0.25:
bbox AP:50.1803, 49.5963, 45.4304
bev  AP:59.9030, 54.7150, 53.2468
3d   AP:59.8010, 54.6809, 53.1366
aos  AP:39.63, 38.13, 35.09
Pedestrian AP_R40@0.50, 0.25, 0.25:
bbox AP:49.2451, 46.8583, 44.1228
bev  AP:59.3406, 55.3669, 52.1828
3d   AP:59.2904, 55.2920, 51.0803
aos  AP:37.15, 34.31, 32.17
Cyclist AP@0.50, 0.50, 0.50:
bbox AP:55.6971, 39.5461, 38.2764
bev  AP:54.8198, 38.2224, 37.1284
3d   AP:53.1655, 37.4204, 36.4887
aos  AP:46.97, 32.58, 31.53
Cyclist AP_R40@0.50, 0.50, 0.50:
bbox AP:55.8919, 37.8161, 33.9657
bev  AP:54.7186, 35.0099, 32.7953
3d   AP:53.0402, 34.0532, 31.7318
aos  AP:46.12, 30.03, 27.06
Cyclist AP@0.50, 0.25, 0.25:
bbox AP:55.6971, 39.5461, 38.2764
bev  AP:55.2914, 38.8157, 37.4016
3d   AP:55.2914, 38.8157, 37.4016
aos  AP:46.97, 32.58, 31.53
Cyclist AP_R40@0.50, 0.25, 0.25:
bbox AP:55.8919, 37.8161, 33.9657
bev  AP:55.2210, 36.9877, 33.1595
3d   AP:55.2210, 36.9877, 33.1595
aos  AP:46.12, 30.03, 27.06
```

Split 2:
```
Car AP@0.70, 0.70, 0.70:
bbox AP:96.6914, 88.7559, 87.1686
bev  AP:89.6414, 85.7397, 79.2499
3d   AP:88.1025, 77.2806, 69.6538
aos  AP:95.96, 87.87, 86.05
Car AP_R40@0.70, 0.70, 0.70:
bbox AP:98.1452, 91.6966, 87.1124
bev  AP:95.1446, 86.3751, 81.5480
3d   AP:91.1320, 77.4718, 72.7242
aos  AP:97.34, 90.72, 85.97
Car AP@0.70, 0.50, 0.50:
bbox AP:96.6914, 88.7559, 87.1686
bev  AP:97.0062, 89.1552, 88.0703
3d   AP:97.5818, 89.0250, 87.5697
aos  AP:95.96, 87.87, 86.05
Car AP_R40@0.70, 0.50, 0.50:
bbox AP:98.1452, 91.6966, 87.1124
bev  AP:98.2979, 94.3327, 89.6986
3d   AP:98.4326, 92.2598, 89.3975
aos  AP:97.34, 90.72, 85.97
Pedestrian AP@0.50, 0.50, 0.50:
bbox AP:57.6434, 52.8282, 47.3798
bev  AP:50.7659, 45.5090, 43.2965
3d   AP:48.7103, 43.6313, 38.8455
aos  AP:44.33, 40.31, 36.23
Pedestrian AP_R40@0.50, 0.50, 0.50:
bbox AP:55.4885, 50.9032, 47.0967
bev  AP:49.5267, 44.7794, 39.9836
3d   AP:46.8996, 41.1147, 37.1701
aos  AP:41.19, 37.13, 33.90
Pedestrian AP@0.50, 0.25, 0.25:
bbox AP:57.6434, 52.8282, 47.3798
bev  AP:60.1065, 58.1532, 52.5542
3d   AP:60.0202, 54.5100, 52.4791
aos  AP:44.33, 40.31, 36.23
Pedestrian AP_R40@0.50, 0.25, 0.25:
bbox AP:55.4885, 50.9032, 47.0967
bev  AP:60.1045, 56.1739, 51.0589
3d   AP:60.0185, 55.0687, 49.9226
aos  AP:41.19, 37.13, 33.90
Cyclist AP@0.50, 0.50, 0.50:
bbox AP:37.7206, 34.5612, 33.7128
bev  AP:33.1583, 29.8266, 29.3790
3d   AP:31.5708, 28.8987, 28.5315
aos  AP:35.55, 32.47, 31.58
Cyclist AP_R40@0.50, 0.50, 0.50:
bbox AP:34.7546, 32.2395, 30.0869
bev  AP:31.0673, 26.7222, 25.0152
3d   AP:28.4158, 25.6330, 23.0792
aos  AP:32.82, 29.64, 27.79
Cyclist AP@0.50, 0.25, 0.25:
bbox AP:37.7206, 34.5612, 33.7128
bev  AP:34.2568, 30.1642, 29.7915
3d   AP:34.2568, 30.1642, 29.7915
aos  AP:35.55, 32.47, 31.58
Cyclist AP_R40@0.50, 0.25, 0.25:
bbox AP:34.7546, 32.2395, 30.0869
bev  AP:31.7888, 28.1894, 25.4120
3d   AP:31.7888, 28.1894, 25.4120
aos  AP:32.82, 29.64, 27.79
```

Which are actually quite comparable to the paper's results:
![image](https://user-images.githubusercontent.com/17109672/124401415-4a294080-dcde-11eb-96e9-295a33bd6961.png)
but not the revised results in the readme:
![image](https://user-images.githubusercontent.com/17109672/124401424-5d3c1080-dcde-11eb-8b75-f5a14857b0a9.png)
which are much lower (lower numbers, at looser IoU threshold) due to fixed ground-truth sampling

I was wondering if you had any ideas why this may be the case?
I didn't even generate the full ground truth database, and during training, I see the line:
```
INFO  Total samples for KITTI dataset: 37
```
So indeed I am training on the reduced split

**Comment by yezhen17** [comment]
> Hello! Thank you for open-sourcing your codebase.
> 
> I have tried to use the repository to first do the pre-training phase on KITTI.
> Actually, first, the repository would not run automatically for me, so I had to make some changes:
> https://github.com/THU17cyz/3DIoUMatch-PVRCNN/blob/b50d9fd932c42e6916d29ad7153f1d3ccbd55827/pcdet/datasets/kitti/kitti_dataset.py#L452
> 
> 
> I changed to training=False (because otherwise, it kept looking for a "kitti_dbinfos_train.pkl", which for some reason I couldn't properly generate with the full split txt - it just gave me an empty list [])
> Here:
> https://github.com/THU17cyz/3DIoUMatch-PVRCNN/blob/b50d9fd932c42e6916d29ad7153f1d3ccbd55827/pcdet/datasets/kitti/kitti_dataset.py#L226
> 
> 
> I added
> ```
> include_info_idxs = None
> if len(self.sample_id_list[0].split(" ")) == 2: # means it's a split
>     # generate stuff to include
>     include_info_idxs = [int(line.split(" ")[1]) for line in self.sample_id_list]
> 
> for k in range(len(infos)):
>     if include_info_idxs is not None:
>         if k not in include_info_idxs:
>             continue
> ```
> 
> because there didn't seem to be any code built-in for filtering just the frames inside the smaller split.
> 
> With these changes, I tried training on the provided 0.01_1 and 0.01_2 splits, and got:
> Split 1:
> 
> ```
> Car AP@0.70, 0.70, 0.70:
> bbox AP:97.0166, 88.4264, 87.7184
> bev  AP:89.7851, 85.1410, 79.3515
> 3d   AP:88.5321, 77.2608, 75.0451
> aos  AP:96.56, 87.50, 86.56
> Car AP_R40@0.70, 0.70, 0.70:
> bbox AP:98.1557, 91.4289, 89.1516
> bev  AP:95.1296, 85.9902, 83.5684
> 3d   AP:91.6326, 79.0419, 74.8542
> aos  AP:97.68, 90.40, 87.91
> Car AP@0.70, 0.50, 0.50:
> bbox AP:97.0166, 88.4264, 87.7184
> bev  AP:97.0982, 88.7778, 88.4398
> 3d   AP:97.0132, 88.7039, 88.2761
> aos  AP:96.56, 87.50, 86.56
> Car AP_R40@0.70, 0.50, 0.50:
> bbox AP:98.1557, 91.4289, 89.1516
> bev  AP:98.2354, 93.8260, 91.6486
> 3d   AP:98.1979, 93.5422, 91.4403
> aos  AP:97.68, 90.40, 87.91
> Pedestrian AP@0.50, 0.50, 0.50:
> bbox AP:50.1803, 49.5963, 45.4304
> bev  AP:42.3984, 37.5393, 35.5838
> 3d   AP:39.5851, 34.8857, 30.8286
> aos  AP:39.63, 38.13, 35.09
> Pedestrian AP_R40@0.50, 0.50, 0.50:
> bbox AP:49.2451, 46.8583, 44.1228
> bev  AP:40.1931, 35.3439, 31.6750
> 3d   AP:36.0652, 31.3460, 28.2745
> aos  AP:37.15, 34.31, 32.17
> Pedestrian AP@0.50, 0.25, 0.25:
> bbox AP:50.1803, 49.5963, 45.4304
> bev  AP:59.9030, 54.7150, 53.2468
> 3d   AP:59.8010, 54.6809, 53.1366
> aos  AP:39.63, 38.13, 35.09
> Pedestrian AP_R40@0.50, 0.25, 0.25:
> bbox AP:49.2451, 46.8583, 44.1228
> bev  AP:59.3406, 55.3669, 52.1828
> 3d   AP:59.2904, 55.2920, 51.0803
> aos  AP:37.15, 34.31, 32.17
> Cyclist AP@0.50, 0.50, 0.50:
> bbox AP:55.6971, 39.5461, 38.2764
> bev  AP:54.8198, 38.2224, 37.1284
> 3d   AP:53.1655, 37.4204, 36.4887
> aos  AP:46.97, 32.58, 31.53
> Cyclist AP_R40@0.50, 0.50, 0.50:
> bbox AP:55.8919, 37.8161, 33.9657
> bev  AP:54.7186, 35.0099, 32.7953
> 3d   AP:53.0402, 34.0532, 31.7318
> aos  AP:46.12, 30.03, 27.06
> Cyclist AP@0.50, 0.25, 0.25:
> bbox AP:55.6971, 39.5461, 38.2764
> bev  AP:55.2914, 38.8157, 37.4016
> 3d   AP:55.2914, 38.8157, 37.4016
> aos  AP:46.97, 32.58, 31.53
> Cyclist AP_R40@0.50, 0.25, 0.25:
> bbox AP:55.8919, 37.8161, 33.9657
> bev  AP:55.2210, 36.9877, 33.1595
> 3d   AP:55.2210, 36.9877, 33.1595
> aos  AP:46.12, 30.03, 27.06
> ```
> 
> Split 2:
> 
> ```
> Car AP@0.70, 0.70, 0.70:
> bbox AP:96.6914, 88.7559, 87.1686
> bev  AP:89.6414, 85.7397, 79.2499
> 3d   AP:88.1025, 77.2806, 69.6538
> aos  AP:95.96, 87.87, 86.05
> Car AP_R40@0.70, 0.70, 0.70:
> bbox AP:98.1452, 91.6966, 87.1124
> bev  AP:95.1446, 86.3751, 81.5480
> 3d   AP:91.1320, 77.4718, 72.7242
> aos  AP:97.34, 90.72, 85.97
> Car AP@0.70, 0.50, 0.50:
> bbox AP:96.6914, 88.7559, 87.1686
> bev  AP:97.0062, 89.1552, 88.0703
> 3d   AP:97.5818, 89.0250, 87.5697
> aos  AP:95.96, 87.87, 86.05
> Car AP_R40@0.70, 0.50, 0.50:
> bbox AP:98.1452, 91.6966, 87.1124
> bev  AP:98.2979, 94.3327, 89.6986
> 3d   AP:98.4326, 92.2598, 89.3975
> aos  AP:97.34, 90.72, 85.97
> Pedestrian AP@0.50, 0.50, 0.50:
> bbox AP:57.6434, 52.8282, 47.3798
> bev  AP:50.7659, 45.5090, 43.2965
> 3d   AP:48.7103, 43.6313, 38.8455
> aos  AP:44.33, 40.31, 36.23
> Pedestrian AP_R40@0.50, 0.50, 0.50:
> bbox AP:55.4885, 50.9032, 47.0967
> bev  AP:49.5267, 44.7794, 39.9836
> 3d   AP:46.8996, 41.1147, 37.1701
> aos  AP:41.19, 37.13, 33.90
> Pedestrian AP@0.50, 0.25, 0.25:
> bbox AP:57.6434, 52.8282, 47.3798
> bev  AP:60.1065, 58.1532, 52.5542
> 3d   AP:60.0202, 54.5100, 52.4791
> aos  AP:44.33, 40.31, 36.23
> Pedestrian AP_R40@0.50, 0.25, 0.25:
> bbox AP:55.4885, 50.9032, 47.0967
> bev  AP:60.1045, 56.1739, 51.0589
> 3d   AP:60.0185, 55.0687, 49.9226
> aos  AP:41.19, 37.13, 33.90
> Cyclist AP@0.50, 0.50, 0.50:
> bbox AP:37.7206, 34.5612, 33.7128
> bev  AP:33.1583, 29.8266, 29.3790
> 3d   AP:31.5708, 28.8987, 28.5315
> aos  AP:35.55, 32.47, 31.58
> Cyclist AP_R40@0.50, 0.50, 0.50:
> bbox AP:34.7546, 32.2395, 30.0869
> bev  AP:31.0673, 26.7222, 25.0152
> 3d   AP:28.4158, 25.6330, 23.0792
> aos  AP:32.82, 29.64, 27.79
> Cyclist AP@0.50, 0.25, 0.25:
> bbox AP:37.7206, 34.5612, 33.7128
> bev  AP:34.2568, 30.1642, 29.7915
> 3d   AP:34.2568, 30.1642, 29.7915
> aos  AP:35.55, 32.47, 31.58
> Cyclist AP_R40@0.50, 0.25, 0.25:
> bbox AP:34.7546, 32.2395, 30.0869
> bev  AP:31.7888, 28.1894, 25.4120
> 3d   AP:31.7888, 28.1894, 25.4120
> aos  AP:32.82, 29.64, 27.79
> ```
> 
> Which are actually quite comparable to the paper's results:
> ![image](https://user-images.githubusercontent.com/17109672/124401415-4a294080-dcde-11eb-96e9-295a33bd6961.png)
> but not the revised results in the readme:
> ![image](https://user-images.githubusercontent.com/17109672/124401424-5d3c1080-dcde-11eb-8b75-f5a14857b0a9.png)
> which are much lower (lower numbers, at looser IoU threshold) due to fixed ground-truth sampling
> 
> I was wondering if you had any ideas why this may be the case?
> I didn't even generate the full ground truth database, and during training, I see the line:
> 
> ```
> INFO  Total samples for KITTI dataset: 37
> ```
> 
> So indeed I am training on the reduced split

Hi @Divadi , can you post the commands you used? And can you post your logging when pre-training?

**Comment by Divadi** [comment]
To generate db, I ran:
```
python -m pcdet.datasets.kitti.kitti_dataset create_part_dbinfos \
tools/cfgs/dataset_configs/kitti_dataset.yaml train_0.01_1
```
(I had to copy over train.txt from somewhere else to generate info files).

Then to train:
```
./scripts/dist_pretrain.sh 2 \
    --cfg_file ./cfgs/kitti_models/pv_rcnn.yaml --split train_0.01_1 \
    --extra_tag train_0.01_1 --ckpt_save_interval 4 --repeat 10 \
    --dbinfos kitti_dbinfos_train_0.01_1_37.pkl
```
and test:
```
./scripts/dist_test.sh 2 \
    --cfg_file ./cfgs/kitti_models/pv_rcnn.yaml \
    --ckpt /home/vision/src/code/3DIoUMatch-PVRCNN/output/cfgs/kitti_models/pv_rcnn/train_0.01_1/ckpt/checkpoint_epoch_80.pth
```

As for logs, here is a screenshot of the tensorboard:
![image](https://user-images.githubusercontent.com/17109672/124680533-76c68f00-de7b-11eb-8d19-1365b2adb4d4.png)
![image](https://user-images.githubusercontent.com/17109672/124680545-7b8b4300-de7b-11eb-9942-151f89d32533.png)

and the log_train is attached
[log_train_20210703-164802.txt](https://github.com/THU17cyz/3DIoUMatch-PVRCNN/files/6773374/log_train_20210703-164802.txt)


Thank you for the help!

**Comment by yezhen17** [comment]
> To generate db, I ran:
> 
> ```
> python -m pcdet.datasets.kitti.kitti_dataset create_part_dbinfos \
> tools/cfgs/dataset_configs/kitti_dataset.yaml train_0.01_1
> ```
> 
> (I had to copy over train.txt from somewhere else to generate info files).
> 
> Then to train:
> 
> ```
> ./scripts/dist_pretrain.sh 2 \
>     --cfg_file ./cfgs/kitti_models/pv_rcnn.yaml --split train_0.01_1 \
>     --extra_tag train_0.01_1 --ckpt_save_interval 4 --repeat 10 \
>     --dbinfos kitti_dbinfos_train_0.01_1_37.pkl
> ```
> 
> and test:
> 
> ```
> ./scripts/dist_test.sh 2 \
>     --cfg_file ./cfgs/kitti_models/pv_rcnn.yaml \
>     --ckpt /home/vision/src/code/3DIoUMatch-PVRCNN/output/cfgs/kitti_models/pv_rcnn/train_0.01_1/ckpt/checkpoint_epoch_80.pth
> ```
> 
> As for logs, here is a screenshot of the tensorboard:
> ![image](https://user-images.githubusercontent.com/17109672/124680533-76c68f00-de7b-11eb-8d19-1365b2adb4d4.png)
> ![image](https://user-images.githubusercontent.com/17109672/124680545-7b8b4300-de7b-11eb-9942-151f89d32533.png)
> 
> and the log_train is attached
> [log_train_20210703-164802.txt](https://github.com/THU17cyz/3DIoUMatch-PVRCNN/files/6773374/log_train_20210703-164802.txt)
> 
> Thank you for the help!

Most evaluation epochs are missing in the log files,  but this is not important. I noticed that the total batch size is 4 instead of 8, which may cause some difference. And the following seems strange:

```
2021-07-03 16:48:02,852   INFO  Database filter by min points Car: 185 => 183
2021-07-03 16:48:02,852   INFO  Database filter by min points Pedestrian: 12 => 12
2021-07-03 16:48:02,852   INFO  Database filter by min points Cyclist: 2 => 2
2021-07-03 16:48:02,853   INFO  Database filter by difficulty Car: 183 => 149
2021-07-03 16:48:02,853   INFO  Database filter by difficulty Pedestrian: 12 => 10
2021-07-03 16:48:02,853   INFO  Database filter by difficulty Cyclist: 2 => 1
```

Can you compare your `train.txt` with the one I just uploaded (which is taken from OpenPCDet)?

Due to some reason I do not have access to the computing resources now. I will look into this closer soon.

**Comment by Divadi** [comment]
I have checked, they are identical
Could I know why the database filter part seems strange?

I terminated the evaluation epochs and just did epoch 80.
I used 2 gpus, so I guess that's why it was 2 x 2 = 4, but I feel that reducing batch size should not dramatically improve performance

**Comment by yezhen17** [comment]
The pedestrians and cyclists left are too few. Have you printed `include_info_idxs` and `len(infos)`? Since you used `training=False`, I'm not very sure what happened then.

**Comment by yezhen17** [comment]
Apologies! Your issue may somehow be related to #5 , since I don't know how you managed to go around the fatal bug. The README.md is updated and if you still feels like running the experiments, please refer to the latest README.md.
