### ISSUE TITLE
3DIoU filter

### ISSUE THREAD

**Issue by wennieWN** [THU17cyz/3DIoUMatch-PVRCNN#10]
Hello, thank you for your codebase!

I am troubled that which part is the 3diou filter. The following code applies 3diou threshold (0.5/0.25/0.25 for car/ped/cyc)， but it seems like class confidence filter.
 
[pv_rcnn_ssl.py line 81](https://github.com/THU17cyz/3DIoUMatch-PVRCNN/blob/main/pcdet/models/detectors/pv_rcnn_ssl.py)
`valid_inds = pseudo_score > conf_thresh.squeeze()`

**Comment by yezhen17** [comment]
Actually it is IoU prediction. You may refer to the PV-RCNN paper: https://arxiv.org/pdf/1912.13192.pdf

![image](https://user-images.githubusercontent.com/52420115/140447895-231fb8bc-11b7-47d4-87f2-9d1c0531ec62.png)
