### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by kuaiqushangzixiba** [THU17cyz/3DIoUMatch-PVRCNN#11]
File "/3DIoUMatch-PVRCNN-main/pcdet/models/detectors/pv_rcnn_ssl.py", line 73, in forward
    pseudo_score = pred_dicts[ind]['pred_scores']
IndexError: list index out of range
![image](https://user-images.githubusercontent.com/42159103/143212773-1b1a6a12-1276-404f-8283-7ba4db4699a2.png)
pv_rcnn_ssl.py,the unlabeled_mask is [2,3,6,7], 
but pred_dicts only have four elements, pred_dicts[ind] may be out of range

**Comment by yezhen17** [comment]
#2

**Comment by kuaiqushangzixiba** [comment]
> #2

Thacks ,  in Supplementary , What does "the number of traverses in each epoch to ten times"  mean?
Reuse the data 10 times ? Or add 10 epochs ?  Sorry, This question looks stupid, but thank you for your answer.

![image](https://user-images.githubusercontent.com/42159103/143732117-6d1e3d24-10fb-4822-90d4-993855940d94.png)

**Comment by yezhen17** [comment]
It means we reuse the dataset 10 times for every epoch.

**Comment by kuaiqushangzixiba** [comment]
why not do the experiments on kitti test?
I try to upload the result to kittiboard , but the result looks too bad...

**Comment by yezhen17** [comment]
How did you obtain the test results? We thought results on val set were convincing enough so did not do the experiments on test set.
