### ISSUE TITLE
Easy question about # self.pv_rcnn_ema.eval()  # Important! must be in train mode

### ISSUE THREAD

**Issue by SII-Whaleice** [THU17cyz/3DIoUMatch-PVRCNN#12]
Hello, i have a simple question?
in pv_rcnn_ssl.py line 55

i am not sure what this code means?  Does it means  i need to uncomment  it when training and annotating it when testing? or just  a reminder aims to state the _ema should be in eval state

**Comment by yezhen17** [comment]
No! keep it commented. Eval mode leads to bad results.

**Comment by SII-Whaleice** [comment]
Thank you！
