### ISSUE TITLE
connot import name iou3d_nms_cuda

### ISSUE THREAD

**Issue by JiangZhenW** [THU17cyz/3DIoUMatch-PVRCNN#15]
thanks for your amazing work! After i deploy the environment successfully, and in the terminal,i can python and import spconv and pcdet successfully.But when i want to run the code, I meet a problem"connot import name iou3d_nms_cuda",how can i solve it?

**Comment by 11910503** [comment]
I know way the error will happen, but I can't solve it. in the project, I don't find the file of iou3d_nms_cuda.py. I think maybe creator delete the file  unconsciously.

**Comment by yezhen17** [comment]
Did you use the correct pcdet version? Also can post a screenshot of your error?

**Comment by JiangZhenW** [comment]
thank you for your replay! i solved this problem by creating this environment again.

**Comment by yezhen17** [comment]
Yes, sometimes you didn't install the correct dependence (e.g. torch/cuda version), and later if you don't remove the build folder this error may occur.
