### ISSUE TITLE
Incorrect unlabeled_index_list initialization in KittiDatasetSSL init?

### ISSUE THREAD

**Issue by fnozarian** [THU17cyz/3DIoUMatch-PVRCNN#16]
Hello,

I noticed that [this line](https://github.com/THU17cyz/3DIoUMatch-PVRCNN/blob/main/pcdet/datasets/kitti/kitti_dataset_ssl.py#L47) does not work as intended. The `self.unlabeled_index_list` is initialized incorrectly because the elements in `self.sample_index_list` are `string`, not `int`. Therefore the set subtraction doesn't remove the labeled items. Can you confirm this?

**Comment by yezhen17** [comment]
https://github.com/THU17cyz/3DIoUMatch-PVRCNN/issues/2#issuecomment-882359285

**Comment by yezhen17** [comment]
Hi @fnozarian , this is a bug indeed but I did not fix it because it is OK to use labeled data in unlabeled data. Please refer to the above discussion
