### ISSUE TITLE
Unlabeled Weight:0

### ISSUE THREAD

**Issue by dof-pikes** [THU17cyz/3DIoUMatch-PVRCNN#18]
Hi! Yezhen Cong:

I tested the model which train with 0 unlabeled weight. The result indicated that the model perform better than 1 unlabeled weight.

Does  0 unlabeled weight means completely learn from labeled data ?   

Thanks!  I'm confused for a long time.

**Comment by yezhen17** [comment]
Sorry for the late reply and thanks for your interest. Yes, 0 unlabeled weight means not supervised by unlabeled data. This could happen because the dataset is very small and the performance fluctuates.

**Comment by dof-pikes** [comment]
Thanks for your reply！
I tried 50% setting, 0  better than 1.

And I visualized the pseudo box which are low quality.

**Comment by yezhen17** [comment]
Well using 50% data, the difference of fully supervised learning should be very small. Adding supervision from unlabeled data may be harmful instead. With a low data ratio where labels are scarce, leveraging pseudo labels from the large amount of unlabeled data would be more helpful.

**Comment by dof-pikes** [comment]
Thanks!
Emm..Maybe low quality pseudo labels are harmful?
Could  you illustrate why you do not  apply IoU optimization ?
"the features fed to the IoU estimation branch are not differentiable w.r.t. the bounding box size."
Because the input of PV-RCNN not seed points?

**Comment by yezhen17** [comment]
Hi @dof-pikes ,

Sorry did not see this comment. Maybe pseudo labels are harmful when there are plenty of true labels as pseudo labels have lower quality. And yes, we find PV-RCNN RoI Grid pooling not differentiable w.r.t bounding box size.
