### ISSUE TITLE
Question about pv_rcnn_ssl.py

### ISSUE THREAD

**Issue by zyrant** [THU17cyz/3DIoUMatch-PVRCNN#19]
hi, i wonder know **batch_dict['gt_boxes'][ind, ...][:, 0:7]** and  **ori_unlabeled_boxes[i, :, 0:7]** represent what.
for **batch_dict['gt_boxes'][ind, ...][:, 0:7]**, it is a pseudo_box from teacher network. 
but for  **ori_unlabeled_boxes[i, :, 0:7]**, does it mean a gt box or what?

```
  anchor_by_gt_overlap = iou3d_nms_utils.boxes_iou3d_gpu(
                        batch_dict['gt_boxes'][ind, ...][:, 0:7],
                        ori_unlabeled_boxes[i, :, 0:7])
```
in pv_rcnn_ssl.py line 149-152.

**Comment by dof-pikes** [comment]
我们可以交流一下，QQ 1206961978

**Comment by SII-Whaleice** [comment]
想听听大佬们是怎么理解的？

**Comment by yezhen17** [comment]
Thanks for the interest in our work! These are just for statistics. ori_unlabeled_boxes are gt and batch_dict['gt_boxes'] are corresponding pseudo label. This is to measure the quality of pseudo labels.

**Comment by zyrant** [comment]
Thx.
