### ISSUE TITLE
Questions about the performance under the 1% and 2% annotations.

### ISSUE THREAD

**Issue by azhuantou** [THU17cyz/3DIoUMatch-PVRCNN#21]
Hello, I'm confused about the performance you report in your paper of arxiv vision and README.
You indicate in your paper that the performance is based on an IoU of 0.7, 0.5, 0.5, but in README it is based on 0.5, 0.25, 0.25.
So which one is real one?
Looking forward to your reply.
Thanks! @THU17cyz 
![image](https://user-images.githubusercontent.com/33474693/180953165-0efe4a65-3a93-4578-a291-5c93d62594c5.png)

**Comment by azhuantou** [comment]
[https://github.com/THU17cyz/3DIoUMatch-PVRCNN/issues/20] (url)

**Comment by yezhen17** [comment]
Hi @azhuantou,

Thanks for your interest and apologies to the inconvenience. The README has been fixed.

The thresholds for calculating mAP are 0.7, 0.5, 0.5, but thresholds for filtering pseudo boxes are 0.5, 0.25, 0.25. I fixed README.
