### ISSUE TITLE
About how to split data

### ISSUE THREAD

**Issue by Creator-wei** [THU17cyz/3DIoUMatch-PVRCNN#23]
when I run 
`python -m pcdet.datasets.kitti.kitti_dataset create_part_dbinfos  /tools/cfgs/dataset_configs/kitti_dataset.yaml train_0.01_1`
there have been two results of splitting the data under different machines. One is only processing 37 sets of data, and the other is processing 3769 sets of data. Which is right here? I understand that the group of 37 is correct, but why does the group of 3769 appear?

**Comment by nomiaro** [comment]
3769 is the number of val samples

**Comment by yezhen17** [comment]
Hi @Creator-wei ,

Thank you for your interest in our work. Yes, @nomiaro is correct. Thanks for the help.
