### ISSUE TITLE
Question about the EMA code

### ISSUE THREAD

**Issue by azhuantou** [THU17cyz/3DIoUMatch-PVRCNN#24]
Hello, thanks for your great work!
I want to know the location of the code change for the ema training manner. 
I find that the teacher model weight update (pv_rcnn_ema) is related to the following code, did I miss anything? 
Looking forward to your reply! @THU17cyz 
![image](https://user-images.githubusercontent.com/33474693/196579314-3da8807e-e8f5-474d-a623-f3cdabceee95.png)

**Comment by yezhen17** [comment]
Hi @azhuantou, thanks for your interest in our work. What do you mean by code change?

And yes, the screenshot is indeed the place for teacher model update.

**Comment by azhuantou** [comment]
Thanks for your reply! @THU17cyz 
I would like to know what you have changed relative to the original PCDet framework in order to use the EMA weight update method. 
Are there some other special operations besides the code in the above picture? 
For example, do not update the batch norm layer or something else.

**Comment by yezhen17** [comment]
I think that's all. I would recommend you use some folder comparison tool such as Meld to compare this repo and the OpenPCDet repo at commit hash a7cf5368d9cbc3969b4613c9e61ba4dcaf217517.

**Comment by azhuantou** [comment]
Thanks for your reply!
