### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by qiaozhijian** [THU17cyz/3DIoUMatch-PVRCNN#3]
Hello, what is your GPU configuration? I trained with 8 GTX 1080Ti GPUs which are same as OpenPCDet, yet running this project reported the following error:
`RuntimeError: CUDA out of memory. Tried to allocate 216.00 MiB (GPU 4; 10.91 GiB total capacity; 6.64 GiB already allocated; 151.38 MiB free; 6.71 GiB reserved in total by PyTorch)
`
By the way, my torch version is 1.5.0 and CUDA version is 9.0.176. 
[link](https://github.com/open-mmlab/OpenPCDet/issues/401) said that pv_rcnn model occupied about 8700-9100M memory usage on each GPU with batch_size=2.

**Comment by yezhen17** [comment]
Hi, 1080Ti doesn't have enough memory. I used V100. SSL training requires more memory than merely training the backbone model.

**Comment by qiaozhijian** [comment]
Thank you.
