### ISSUE TITLE
Data split generation

### ISSUE THREAD

**Issue by honggyuchoi** [THU17cyz/3DIoUMatch-PVRCNN#5]
Hello, Thank you for your nice work.

I have a problem in data preprocessing.

When i ran the data preprocessing code with the below command,
`python -m pcdet.datasets.kitti.kitti_dataset create_part_dbinfos tools/cfgs/dataset_configs/kitti_dataset.yaml split_0.01_1` 

But I got this error,

<img width="957" alt="image" src="https://user-images.githubusercontent.com/42855032/128819511-5bb64e73-ca54-4206-b94f-f494f1718928.png">

Then, I ran the data infos generator code from original "OpenPCDet" repository for generating "kitti_dbinfos_train.pkl"

`python -m pcdet.datasets.kitti.kitti_dataset create_kitti_infos tools/cfgs/dataset_configs/kitti_dataset.yaml`

But, when i ran this code, "kitti_dbinfos_train_3712.pkl" is made. 

How i can solve this problem? Could you help me?

**Comment by yezhen17** [comment]
Please rename 'kitti_dbinfos_train_3712.pkl' to 'kitti_dbinfos_train.pkl'.

**Comment by honggyuchoi** [comment]
Thank you!

**Comment by yezhen17** [comment]
Hi @honggyuchoi , I updated README.md. A silly mistake was made that I forgot to include the command to generate the `infos` and `dbinfos` file in README.md, which is what you mentioned in your solution. Then the most convenient workaround is to rename the file.

**Comment by yezhen17** [comment]
Thank you very much for helping me find this bug!
