### ISSUE TITLE
When i modified code to use batch_size 4 in ssl and try to reproduce your results, results look weird. 

### ISSUE THREAD

**Issue by honggyuchoi** [THU17cyz/3DIoUMatch-PVRCNN#9]
Hi  @THU17cyz  

I have trouble when i reproduces SSL with 0.02 data. 

I modified the code to use batch_size 4 in one gpu.

Then, I pre-trained and trained model with 0.02 split data that uploaded in your repository.

In conclusion, I modified the batch size(16->4) 
I am not modified other setting(i.e. epochs, learning rate)

I think pre-trained model looks well, but ssl trained model does not looks good. 

The first table is my pre-trained model's results, and the second one is my ssl-trained model's results.
I report the accuracy of the last epoch model.

<img width="767" alt="image" src="https://user-images.githubusercontent.com/42855032/138380473-b290038c-aad6-46fa-a0f0-27d834c234ea.png">

Performance of cyclist is improved, but pedestrian's is decreased. 

I only modified the code like this.
`kitti_dataset_ssl.py line: 46`

        if self.training:
            all_train = len(self.kitti_infos)
            #self.unlabeled_index_list = list(set(list(range(all_train))) - set(self.sample_index_list))  # float()!!!
            self.unlabeled_index_list = list(set(list(range(all_train))) - set([int(i) for i in self.sample_index_list]))
            # print(self.unlabeled_index_list)
            self.unlabeled_kitti_infos = []

Remove labeled data index from unlabeled_index_list.

`kitti_dataset_ssl.py line: 390`

        if self.training:
            #index_unlabeled = np.random.choice(self.unlabeled_index_list, 1)[0]
            index_unlabeled = np.random.choice(len(self.unlabeled_kitti_infos), 1)[0]
            info_unlabeled = copy.deepcopy(self.unlabeled_kitti_infos[index_unlabeled])

            data_dict_unlabeled = self.get_item_single(info_unlabeled, no_db_sample=True)
            return [data_dict_labeled, data_dict_unlabeled]
        else:
            return data_dict_labeled

np.random.choice(self.unlabeled_index_list,1)[0] => np.random.choice(len(self.unlabeled_kitti_infos),1)[0]

`In pv_rcnn_ssl.py line: 38`

    if self.training:
            batch_dict['mask'] = batch_dict['mask'][:, :1] #  modify by chenxyyyy #modified by Honggyu
            mask = batch_dict['mask'].view(-1)

I add  batch_dict['mask'] = batch_dict['mask'][:, :1]  according to #2 (also about pseudo_sem_scores is modified)

`In pv_rcnn_ssl.py line: 215`

             if not self.unlabeled_supervise_cls:
                loss_rpn_cls = loss_rpn_cls[labeled_mask, ...].mean() #modified by Honggyu
            else:
                loss_rpn_cls = loss_rpn_cls[labeled_mask, ...].mean() + loss_rpn_cls[unlabeled_mask, ...].mean() * self.unlabeled_weight #modified by Honggyu

            loss_rpn_box = loss_rpn_box[labeled_mask, ...].mean() + loss_rpn_box[unlabeled_mask, ...].mean() * self.unlabeled_weight #modified by Honggyu
            loss_point = loss_point[labeled_mask, ...].mean() #modified by Honggyu
            loss_rcnn_cls = loss_rcnn_cls[labeled_mask, ...].mean() #modified by Honggyu

            if not self.unlabeled_supervise_refine:
                loss_rcnn_box = loss_rcnn_box[labeled_mask, ...].mean() #modified by Honggyu
            else:
                loss_rcnn_box = loss_rcnn_box[labeled_mask, ...].mean() + loss_rcnn_box[unlabeled_mask, ...].mean() * self.unlabeled_weight #modified by Honggyu

            loss = loss_rpn_cls + loss_rpn_box + loss_point + loss_rcnn_cls + loss_rcnn_box
            tb_dict_ = {}
            for key in tb_dict.keys():
                if 'loss' in key:
                    tb_dict_[key+"_labeled"] = tb_dict[key][labeled_mask, ...].mean() #modified by Honggyu
                    tb_dict_[key + "_unlabeled"] = tb_dict[key][unlabeled_mask, ...].mean() #modified by Honggyu
                elif 'acc' in key:
                    tb_dict_[key+"_labeled"] = tb_dict[key][labeled_mask, ...].mean() #modified by Honggyu
                    tb_dict_[key + "_unlabeled"] = tb_dict[key][unlabeled_mask, ...].mean() #modified by Honggyu
                elif 'point_pos_num' in key:
                    tb_dict_[key + "_labeled"] = tb_dict[key][labeled_mask, ...].mean() #modified by Honggyu
                    tb_dict_[key + "_unlabeled"] = tb_dict[key][unlabeled_mask, ...].mean() #modified by Honggyu
                else:
                    tb_dict_[key] = tb_dict[key]

            tb_dict_['pseudo_ious'] = torch.cat(pseudo_ious, dim=0).mean()
            tb_dict_['pseudo_accs'] = torch.cat(pseudo_accs, dim=0).mean()
            # tb_dict_['sem_score_fg'] = sem_score_fg.mean()
            # tb_dict_['sem_score_bg'] = sem_score_bg.mean()
            tb_dict_['sem_score_fg'] = torch.cat(pseudo_sem_score_fg, dim=0).mean() #modified by Honggyu
            tb_dict_['sem_score_bg'] = torch.cat(pseudo_sem_score_bg, dim=0).mean() #modified by Honggyu

I modified .sum() to .mean() to compute loss.

And i modified batch_size = 2 to batch_size = 4 according to #2 

And in pv_rcnn_ssl_60.yaml,
OPTIMIZATION.BATCH_SIZE_PER_GPU = 2.

Questions
1. Is my modification valid?
2. In your paper, is all reported performance from the last epoch model or from the best accuracy model?
If you chose the best accuracy model, how do you define? Averaging all 3d bounding box accuracy?

Additionally, the model's performance fluctuates too much. Is it because the amount of labeled data is too small?(1%, 2%). or Is it because the learning rate is too high? or is it because my batch_size is too small? What do you think about it.

Here is my tensorboard results. ( _teacher is performance of teacher network)

SSL Trained model 0.02_1 in your repo. 
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/42855032/138382767-faf2c744-2afb-42a9-83d8-d094f6759716.png">
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/42855032/138382817-0d0e657d-fd5b-4fb1-9074-7af6c0265df0.png">
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/42855032/138382844-fefc80bf-2d31-40b9-a111-e54f7b8cd26b.png">
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/42855032/138383021-9aea0ac9-8337-49fc-bb0b-363fc7e6b044.png">

SSL Trained model 0.02_2 in your repo. 

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/42855032/138383110-2b6ced39-4f23-4c14-add7-f684a5f931ee.png">
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/42855032/138383134-16f64a26-cf83-4d30-94d5-f0b8c6a9b797.png">
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/42855032/138383141-b56ca09f-bc4c-4719-a22d-3ef42b5c48a1.png">
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/42855032/138383151-d3256739-7386-4f4b-b091-3920f3fec6cc.png">

SSL Trained model 0.02_3 in your repo. 
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/42855032/138383190-7a1c430b-29e2-4437-bb6c-4b5b048e0eaf.png">
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/42855032/138383216-9f21186d-e12e-4f61-ba03-7fcbefa6369b.png">
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/42855032/138383230-a9b3c72f-d0a7-4e75-8358-bea4349f5e48.png">
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/42855032/138383249-8ff70f8e-027b-42dd-92e1-dde688baa7c8.png">

**Comment by yezhen17** [comment]
Hi @honggyuchoi ,

1. So what batch size (in total, batch_size_per_gpu * num_gpus) are you using? Again, changing batch size may lead to unknown performance change. A rule someone very experienced once told me is that in some cases, you can try to scale the learning rate linearly to batch size.
2. I reported best performance for all settings. Indeed the fluctuation is large. I mentioned before that a better way is to average on 3 different runs on one split and then average on 3 splits. 
3. For KITTI, 1% means <40 samples, so the large fluctuation is expected. Actually, I hardly tuned with the learning rate and batch size. I believe after careful tuning the performance may slightly improve.
4. Regarding your modifications:
  - Remove labeled data index from unlabeled_index_list. I think it is OK.
  - `kitti_dataset_ssl.py line: 390` Since unlabeled_index_list is not full data, this modification is necessary.
  - `pv_rcnn_ssl.py line: 38` Nothing wrong to me.
  - `pv_rcnn_ssl.py line: 215` Looks good to me. 

My tensorboard results (only the performance) on 3 splits of 2% data:
![image](https://user-images.githubusercontent.com/52420115/138588619-6b819d3f-0f65-4b3e-ac8b-a59cdefdd45e.png)
![image](https://user-images.githubusercontent.com/52420115/138588644-fd0e40e8-759f-408c-94b9-8a42d6d7592e.png)
![image](https://user-images.githubusercontent.com/52420115/138588654-3379ee4b-73d6-402c-ae01-0c55c94fb39b.png)

Judging from the difference between our tensorboard curves, probably you can consider changing the batch size or learning rate?

**Comment by honggyuchoi** [comment]
Thank you for reply.

1. My total batch size is 4(labeled 2 + unlabeled 2). Then, do I have to reduce learning rate by 4 times?  Actually, i am applying 'gradient accumulation' to reduce the gap. I don't have results now, but it will give results soon.

2. It could be a silly question. Then, how to select the best model? Average all 3D_R40 performance?( Averaging car_easy, car_mid, car_hard, ped_easy, ped_mid, ped_hard, cyc_easy, cyc_mid, cyc_hard)

Then, I think that I need more gpus or need to try to tune the learning rate to reproduce your results.
Thank you for your kindness and helpful advise!

**Comment by yezhen17** [comment]
I actually picked the model with the best average moderate difficulty 3D R40 performance.

Applying gradient accumulation sounds good to me. And yes, maybe you can try reducing lr by 4 times.

**Comment by honggyuchoi** [comment]
Thank you!!

Then, if gradient accumulation doesn't work, i will try reducting lr by 4 times.

Thank you for your kind reply!

**Comment by kuaiqushangzixiba** [comment]
pseudo_sem_score_fg, where defined this, thanks! i dont understand

**Comment by kuaiqushangzixiba** [comment]
> Thank you!!
> 
> Then, if gradient accumulation doesn't work, i will try reducting lr by 4 times.
> 
> Thank you for your kind reply!



> Hi @THU17cyz
> 
> I have trouble when i reproduces SSL with 0.02 data.
> 
> I modified the code to use batch_size 4 in one gpu.
> 
> Then, I pre-trained and trained model with 0.02 split data that uploaded in your repository.
> 
> In conclusion, I modified the batch size(16->4) I am not modified other setting(i.e. epochs, learning rate)
> 
> I think pre-trained model looks well, but ssl trained model does not looks good.
> 
> The first table is my pre-trained model's results, and the second one is my ssl-trained model's results. I report the accuracy of the last epoch model.
> 
> <img alt="image" width="767" src="https://user-images.githubusercontent.com/42855032/138380473-b290038c-aad6-46fa-a0f0-27d834c234ea.png">
> 
> Performance of cyclist is improved, but pedestrian's is decreased.
> 
> I only modified the code like this. `kitti_dataset_ssl.py line: 46`
> 
> ```
>     if self.training:
>         all_train = len(self.kitti_infos)
>         #self.unlabeled_index_list = list(set(list(range(all_train))) - set(self.sample_index_list))  # float()!!!
>         self.unlabeled_index_list = list(set(list(range(all_train))) - set([int(i) for i in self.sample_index_list]))
>         # print(self.unlabeled_index_list)
>         self.unlabeled_kitti_infos = []
> ```
> 
> Remove labeled data index from unlabeled_index_list.
> 
> `kitti_dataset_ssl.py line: 390`
> 
> ```
>     if self.training:
>         #index_unlabeled = np.random.choice(self.unlabeled_index_list, 1)[0]
>         index_unlabeled = np.random.choice(len(self.unlabeled_kitti_infos), 1)[0]
>         info_unlabeled = copy.deepcopy(self.unlabeled_kitti_infos[index_unlabeled])
> 
>         data_dict_unlabeled = self.get_item_single(info_unlabeled, no_db_sample=True)
>         return [data_dict_labeled, data_dict_unlabeled]
>     else:
>         return data_dict_labeled
> ```
> 
> np.random.choice(self.unlabeled_index_list,1)[0] => np.random.choice(len(self.unlabeled_kitti_infos),1)[0]
> 
> `In pv_rcnn_ssl.py line: 38`
> 
> ```
> if self.training:
>         batch_dict['mask'] = batch_dict['mask'][:, :1] #  modify by chenxyyyy #modified by Honggyu
>         mask = batch_dict['mask'].view(-1)
> ```
> 
> I add batch_dict['mask'] = batch_dict['mask'][:, :1] according to #2 (also about pseudo_sem_scores is modified)
> 
> `In pv_rcnn_ssl.py line: 215`
> 
> ```
>          if not self.unlabeled_supervise_cls:
>             loss_rpn_cls = loss_rpn_cls[labeled_mask, ...].mean() #modified by Honggyu
>         else:
>             loss_rpn_cls = loss_rpn_cls[labeled_mask, ...].mean() + loss_rpn_cls[unlabeled_mask, ...].mean() * self.unlabeled_weight #modified by Honggyu
> 
>         loss_rpn_box = loss_rpn_box[labeled_mask, ...].mean() + loss_rpn_box[unlabeled_mask, ...].mean() * self.unlabeled_weight #modified by Honggyu
>         loss_point = loss_point[labeled_mask, ...].mean() #modified by Honggyu
>         loss_rcnn_cls = loss_rcnn_cls[labeled_mask, ...].mean() #modified by Honggyu
> 
>         if not self.unlabeled_supervise_refine:
>             loss_rcnn_box = loss_rcnn_box[labeled_mask, ...].mean() #modified by Honggyu
>         else:
>             loss_rcnn_box = loss_rcnn_box[labeled_mask, ...].mean() + loss_rcnn_box[unlabeled_mask, ...].mean() * self.unlabeled_weight #modified by Honggyu
> 
>         loss = loss_rpn_cls + loss_rpn_box + loss_point + loss_rcnn_cls + loss_rcnn_box
>         tb_dict_ = {}
>         for key in tb_dict.keys():
>             if 'loss' in key:
>                 tb_dict_[key+"_labeled"] = tb_dict[key][labeled_mask, ...].mean() #modified by Honggyu
>                 tb_dict_[key + "_unlabeled"] = tb_dict[key][unlabeled_mask, ...].mean() #modified by Honggyu
>             elif 'acc' in key:
>                 tb_dict_[key+"_labeled"] = tb_dict[key][labeled_mask, ...].mean() #modified by Honggyu
>                 tb_dict_[key + "_unlabeled"] = tb_dict[key][unlabeled_mask, ...].mean() #modified by Honggyu
>             elif 'point_pos_num' in key:
>                 tb_dict_[key + "_labeled"] = tb_dict[key][labeled_mask, ...].mean() #modified by Honggyu
>                 tb_dict_[key + "_unlabeled"] = tb_dict[key][unlabeled_mask, ...].mean() #modified by Honggyu
>             else:
>                 tb_dict_[key] = tb_dict[key]
> 
>         tb_dict_['pseudo_ious'] = torch.cat(pseudo_ious, dim=0).mean()
>         tb_dict_['pseudo_accs'] = torch.cat(pseudo_accs, dim=0).mean()
>         # tb_dict_['sem_score_fg'] = sem_score_fg.mean()
>         # tb_dict_['sem_score_bg'] = sem_score_bg.mean()
>         tb_dict_['sem_score_fg'] = torch.cat(pseudo_sem_score_fg, dim=0).mean() #modified by Honggyu
>         tb_dict_['sem_score_bg'] = torch.cat(pseudo_sem_score_bg, dim=0).mean() #modified by Honggyu
> ```
> 
> I modified .sum() to .mean() to compute loss.
> 
> And i modified batch_size = 2 to batch_size = 4 according to #2
> 
> And in pv_rcnn_ssl_60.yaml, OPTIMIZATION.BATCH_SIZE_PER_GPU = 2.
> 
> Questions
> 
> 1. Is my modification valid?
> 2. In your paper, is all reported performance from the last epoch model or from the best accuracy model?
>    If you chose the best accuracy model, how do you define? Averaging all 3d bounding box accuracy?
> 
> Additionally, the model's performance fluctuates too much. Is it because the amount of labeled data is too small?(1%, 2%). or Is it because the learning rate is too high? or is it because my batch_size is too small? What do you think about it.
> 
> Here is my tensorboard results. ( _teacher is performance of teacher network)
> 
> SSL Trained model 0.02_1 in your repo. <img alt="image" width="1078" src="https://user-images.githubusercontent.com/42855032/138382767-faf2c744-2afb-42a9-83d8-d094f6759716.png"> <img alt="image" width="1036" src="https://user-images.githubusercontent.com/42855032/138382817-0d0e657d-fd5b-4fb1-9074-7af6c0265df0.png"> <img alt="image" width="1056" src="https://user-images.githubusercontent.com/42855032/138382844-fefc80bf-2d31-40b9-a111-e54f7b8cd26b.png"> <img alt="image" width="1050" src="https://user-images.githubusercontent.com/42855032/138383021-9aea0ac9-8337-49fc-bb0b-363fc7e6b044.png">
> 
> SSL Trained model 0.02_2 in your repo.
> 
> <img alt="image" width="1055" src="https://user-images.githubusercontent.com/42855032/138383110-2b6ced39-4f23-4c14-add7-f684a5f931ee.png">
> 
> <img alt="image" width="1068" src="https://user-images.githubusercontent.com/42855032/138383134-16f64a26-cf83-4d30-94d5-f0b8c6a9b797.png">
> 
> <img alt="image" width="1050" src="https://user-images.githubusercontent.com/42855032/138383141-b56ca09f-bc4c-4719-a22d-3ef42b5c48a1.png">
> 
> <img alt="image" width="1033" src="https://user-images.githubusercontent.com/42855032/138383151-d3256739-7386-4f4b-b091-3920f3fec6cc.png">
> 
> SSL Trained model 0.02_3 in your repo. <img alt="image" width="1049" src="https://user-images.githubusercontent.com/42855032/138383190-7a1c430b-29e2-4437-bb6c-4b5b048e0eaf.png"> <img alt="image" width="1050" src="https://user-images.githubusercontent.com/42855032/138383216-9f21186d-e12e-4f61-ba03-7fcbefa6369b.png"> <img alt="image" width="1049" src="https://user-images.githubusercontent.com/42855032/138383230-a9b3c72f-d0a7-4e75-8358-bea4349f5e48.png"> <img alt="image" width="1036" src="https://user-images.githubusercontent.com/42855032/138383249-8ff70f8e-027b-42dd-92e1-dde688baa7c8.png">

pseudo_sem_score_fg, where defined this, thanks! i dont understand

**Comment by honggyuchoi** [comment]
I just defined it for my research. So, it is not important. 

<img width="703" alt="image" src="https://user-images.githubusercontent.com/42855032/146889584-01598c55-b819-4b91-ace2-e36069fcde4c.png">

**Comment by honggyuchoi** [comment]
> pseudo_sem_score_fg, where defined this, thanks! i dont understand

I just defined it for my research. So, it is not important. 

<img width="703" alt="image" src="https://user-images.githubusercontent.com/42855032/146889584-01598c55-b819-4b91-ace2-e36069fcde4c.png">

**Comment by adv010** [comment]
> Thank you!!
> 
> Then, if gradient accumulation doesn't work, i will try reducting lr by 4 times.
> 
> Thank you for your kind reply!

@honggyuchoi did you try the gradient accumulation method any further? That seems to be an interesting direction ! :)
